### ISSUE TITLE
Asset Library?

### ISSUE THREAD

**Issue by HotariTobu** [jamie-pate/godot-control-data-binds#6]
I cannot find this project in [Godot Asset Library](https://godotengine.org/asset-library/asset).
Did you not upload it?

**Comment by jamie-pate** [comment]
I haven't, and I initially thought it would be a bunch of work, but their system is pretty slick!

https://godotengine.org/asset-library/asset/14276 (pending approval)

**Comment by HotariTobu** [comment]
I cannot access the pending page probably because of the permission, but you submitted it just a few hours ago, right?
I hope your so nice asset will be available via Godot Asset Library!

**Comment by jamie-pate** [comment]
https://godotengine.org/asset-library/asset/3434
